from __future__ import annotations

from src.engine.models import MultiplierType

# JSON schema for Claude Vision structured output.
# Used with output_config.format.type = "json_schema" in the Claude API call.
# The schema constrains Claude's token generation to produce only valid JSON
# matching this structure — parse errors are impossible on the primary path.
BOARD_SCHEMA: dict = {
    "type": "object",
    "properties": {
        "board": {
            "type": "object",
            "description": "Bounding rectangle of the occupied board area with all placed cells",
            "properties": {
                "min_row": {"type": "integer", "description": "Smallest row index of any placed tile"},
                "max_row": {"type": "integer", "description": "Largest row index of any placed tile"},
                "min_col": {"type": "integer", "description": "Smallest column index of any placed tile"},
                "max_col": {"type": "integer", "description": "Largest column index of any placed tile"},
                "cells": {
                    "type": "array",
                    "description": "All cells that contain a placed tile",
                    "items": {
                        "type": "object",
                        "properties": {
                            "row": {"type": "integer", "description": "0-indexed row (0 = top)"},
                            "col": {"type": "integer", "description": "0-indexed column (0 = left)"},
                            "letter": {"type": "string", "description": "Uppercase letter on the tile"},
                            "is_blank": {
                                "type": "boolean",
                                "description": "True if this tile is a blank tile playing as the given letter",
                            },
                            "multiplier": {
                                "type": "string",
                                "enum": ["NONE", "DL", "TL", "DW", "TW"],
                                "description": "Square multiplier visible at this board position",
                            },
                        },
                        "required": ["row", "col", "letter", "is_blank", "multiplier"],
                        "additionalProperties": False,
                    },
                },
            },
            "required": ["min_row", "max_row", "min_col", "max_col", "cells"],
            "additionalProperties": False,
        },
        "rack": {
            "type": "array",
            "items": {"type": "string"},
            "description": "Player's tile rack — list of uppercase letter strings, max 7 tiles",
        },
    },
    "required": ["board", "rack"],
    "additionalProperties": False,
}


# Official 19-row x 27-column Letter League board multiplier layout.
# Source: kamilmielnik/scrabble-solver letterLeague config (authoritative).
# Maps (row, col) → multiplier string for all non-NONE squares.
# Only non-NONE positions are included; any (row, col) absent from this dict is NONE.
# Positions are 0-indexed: row 0 = top row, col 0 = leftmost column.
# Center star at (9,13) is NOT a multiplier — it's just the starting position.
# Green squares = DW (Double Word), Orange squares = TL (Triple Letter).
OFFICIAL_MULTIPLIER_LAYOUT: dict[tuple[int, int], str] = {
    # TW — Triple Word (4 squares)
    (3, 7): "TW",
    (3, 19): "TW",
    (15, 7): "TW",
    (15, 19): "TW",
    # DW — Double Word (36 squares, green on board)
    (1, 5): "DW",
    (1, 9): "DW",
    (1, 17): "DW",
    (1, 21): "DW",
    (3, 1): "DW",
    (3, 13): "DW",
    (3, 25): "DW",
    (5, 5): "DW",
    (5, 9): "DW",
    (5, 17): "DW",
    (5, 21): "DW",
    (7, 4): "DW",
    (7, 10): "DW",
    (7, 16): "DW",
    (7, 22): "DW",
    (9, 3): "DW",
    (9, 7): "DW",
    (9, 11): "DW",
    (9, 15): "DW",
    (9, 19): "DW",
    (9, 23): "DW",
    (11, 4): "DW",
    (11, 10): "DW",
    (11, 16): "DW",
    (11, 22): "DW",
    (13, 5): "DW",
    (13, 9): "DW",
    (13, 17): "DW",
    (13, 21): "DW",
    (15, 1): "DW",
    (15, 13): "DW",
    (15, 25): "DW",
    (17, 5): "DW",
    (17, 9): "DW",
    (17, 17): "DW",
    (17, 21): "DW",
    # TL — Triple Letter (28 squares, orange on board)
    (2, 6): "TL",
    (2, 8): "TL",
    (2, 18): "TL",
    (2, 20): "TL",
    (4, 6): "TL",
    (4, 8): "TL",
    (4, 18): "TL",
    (4, 20): "TL",
    (8, 0): "TL",
    (8, 2): "TL",
    (8, 12): "TL",
    (8, 14): "TL",
    (8, 24): "TL",
    (8, 26): "TL",
    (10, 0): "TL",
    (10, 2): "TL",
    (10, 12): "TL",
    (10, 14): "TL",
    (10, 24): "TL",
    (10, 26): "TL",
    (14, 6): "TL",
    (14, 8): "TL",
    (14, 18): "TL",
    (14, 20): "TL",
    (16, 6): "TL",
    (16, 8): "TL",
    (16, 18): "TL",
    (16, 20): "TL",
    # DL — Double Letter (76 squares, blue on board)
    (0, 3): "DL",
    (0, 6): "DL",
    (0, 8): "DL",
    (0, 11): "DL",
    (0, 15): "DL",
    (0, 18): "DL",
    (0, 20): "DL",
    (0, 23): "DL",
    (1, 1): "DL",
    (1, 13): "DL",
    (1, 25): "DL",
    (2, 4): "DL",
    (2, 10): "DL",
    (2, 16): "DL",
    (2, 22): "DL",
    (3, 0): "DL",
    (3, 2): "DL",
    (3, 12): "DL",
    (3, 14): "DL",
    (3, 24): "DL",
    (3, 26): "DL",
    (4, 4): "DL",
    (4, 10): "DL",
    (4, 16): "DL",
    (4, 22): "DL",
    (5, 1): "DL",
    (5, 13): "DL",
    (5, 25): "DL",
    (6, 3): "DL",
    (6, 6): "DL",
    (6, 8): "DL",
    (6, 11): "DL",
    (6, 15): "DL",
    (6, 18): "DL",
    (6, 20): "DL",
    (6, 23): "DL",
    (8, 7): "DL",
    (8, 19): "DL",
    (10, 7): "DL",
    (10, 19): "DL",
    (12, 3): "DL",
    (12, 6): "DL",
    (12, 8): "DL",
    (12, 11): "DL",
    (12, 15): "DL",
    (12, 18): "DL",
    (12, 20): "DL",
    (12, 23): "DL",
    (13, 1): "DL",
    (13, 13): "DL",
    (13, 25): "DL",
    (14, 4): "DL",
    (14, 10): "DL",
    (14, 16): "DL",
    (14, 22): "DL",
    (15, 0): "DL",
    (15, 2): "DL",
    (15, 12): "DL",
    (15, 14): "DL",
    (15, 24): "DL",
    (15, 26): "DL",
    (16, 4): "DL",
    (16, 10): "DL",
    (16, 16): "DL",
    (16, 22): "DL",
    (17, 1): "DL",
    (17, 13): "DL",
    (17, 25): "DL",
    (18, 3): "DL",
    (18, 6): "DL",
    (18, 8): "DL",
    (18, 11): "DL",
    (18, 15): "DL",
    (18, 18): "DL",
    (18, 20): "DL",
    (18, 23): "DL",
}


# Maps schema multiplier strings to the engine's MultiplierType enum.
# Used when populating a Board from vision-extracted data.
MULT_STR_TO_ENGINE: dict[str, MultiplierType] = {
    "NONE": MultiplierType.NONE,
    "DL": MultiplierType.DL,
    "TL": MultiplierType.TL,
    "DW": MultiplierType.DW,
    "TW": MultiplierType.TW,
}
